name: sklansky
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/stevenmburns/rohd_sklansky

environment:
  sdk: '>=2.18.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.17.0
  rohd: ^0.4.0
